pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-cred')
        AWS_SECRET_ACCESS_KEY = credentials('aws-cred')
        AWS_DEFAULT_REGION     = "ap-south-1"
    }

    stages {

        stage('Checkout infra repo') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/main"]],
                    userRemoteConfigs: [[
                        url: "https://github.com/GalamManesha/modules-concepts.git"
                    ]]
                ])
            }
        }

        stage('Fetch module') {
            steps {
                script {
                    sh """
                        rm -rf module/modules/module
                        mkdir -p module/modules/module
                        rsync -a module/modules/module/ module/modules/module/
                    """
                }
            }
        }

        stage('Terraform Init') {
            steps {
                dir('module') {
                    withCredentials([usernamePassword(credentialsId: 'aws-cred',
                                                     usernameVariable: 'AWS_ACCESS_KEY_ID',
                                                     passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        sh """
                            terraform init
                        """
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('module') {
                    withCredentials([usernamePassword(credentialsId: 'aws-cred',
                                                     usernameVariable: 'AWS_ACCESS_KEY_ID',
                                                     passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        sh """
                            terraform plan -out=tfplan
                        """
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('module') {
                    withCredentials([usernamePassword(credentialsId: 'aws-cred',
                                                     usernameVariable: 'AWS_ACCESS_KEY_ID',
                                                     passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        sh """
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
    }
}
